name: Create PR for release

# On an hourly basis, this workflow is triggered. It checks the latest release
# on https://github.com/IBM/openapi-validator/releases. For the latest release,
# if no branch or tag exists locally for that release (e.g. "v0.19.0"), then a
# new branch is created and PR opened to bump the version.

on: repository_dispatch

jobs:
  latest-version:
    name: Do work
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Fetch all git history
      run: git fetch --prune --unshallow

    - name: Get latest openapi-validator tag
      id: latest_tag
      uses: abatilo/release-info-action@v1.1.0
      with:
        owner: IBM
        repo: openapi-validator

    - name: Debug, show latest version
      run: |
        echo "LATEST_TAG='${{ steps.latest_tag.outputs.latest_tag }}'"

    - name: Check for existing tag, update Dockerfile
      continue-on-error: true
      run: |
        ./update.sh ${{ steps.latest_tag.outputs.latest_tag }}

    - name: Create PR for new release
      if: success()
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Bump to ${{ steps.latest_tag.outputs.latest_tag }}"
        title: "Bump to ${{ steps.latest_tag.outputs.latest_tag }}"
        branch: "${{ steps.latest_tag.outputs.latest_tag }}"
