name: Create tag version

# Extracts current version from Dockerfile "ARG version=" line and uses it to
# create a tag.

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jaliborc/action-general-autotag@1.0.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        source_file: "Dockerfile"
        extraction_regex: "ARG version=(\\d+\\.\\d+\\.\\d+)"
        tag_format: "v{version}"
